Repository MIT-Emerging-Talent/ET6-foundations-group-23, pull requests merged in 2025-01, with the labels that each got.

#38 Sync Repo
  .github/PULL_REQUEST_TEMPLATE.md
Labels: update

#44 solving the challenge of checking if a word has double letter
  solutions/double_letter.py
  solutions/tests/test_double_letter.py
Labels: challenge

#39 Length of longest substring
  solutions/length_of_longest_substring.py
  solutions/tests/test_length_of_longest_substring.py
Labels: challenge

#49 Add most frequent character and corresponding test units
  solutions/most_frequent_character.py
  solutions/tests/test_most_frequent_character.py
Labels: challenge

#40 [FEAT] added max_area problem
  solutions/max_area.py
  solutions/tests/test_max_area.py
Labels: challenge

#52 checking if the number is square number
  .vscode/settings.json
  collaboration/guide/0_repository_setup.md
  solutions/tests/test_is_square.py
Labels: challenge

#60 Update communication.md
  collaboration/communication.md
Labels: documentation, communication, update

#58 Nameamdfunfact
  README.md
Labels: documentation, communication

#62 47 pascal triangle interview challenge
  solutions/pascal_triangle.py
  solutions/tests/test_pascal_triangle.py
Labels: challenge

#66 is_prime solution
  solutions/is_prime.py
  solutions/tests/test_is_prime.py
Labels: challenge

#56 fix config error
  .github/PULL_REQUEST_TEMPLATE.md
  .vscode/settings.json
Labels: update

#72 Update README.md
  README.md
Labels: documentation

#30 All team readme
  README.md
Labels: documentation

#86 chore: remove solution files and tests which have not been revewied
  solutions/check_straight_line.py
  solutions/max_coders_chessboard.py
  solutions/tests/test_check_straight_line.py
  solutions/tests/test_max_coders_chessboard.py
Labels: Polish, delete

#85 Reorganize group norms file
  collaboration/README.md
Labels: norms, communication, update

#91 Add learning goals
  README.md
  collaboration/learning_goals.md
Labels: documentation

#78 sum_proper_divisors solution
  solutions/sum_proper_divisors.py
  solutions/tests/test_sum_proper_divisors.py
Labels: challenge

#82 Vowel Counter
  solutions/tests/test_vowel_counter.py
  solutions/vowel_counter.py
Labels: challenge

#70 Palindrome Checker
  solutions/palindrome_checker.py
  solutions/tests/test_palindrome_checker.py
Labels: challenge

#92 Update main README.md file
  README.md
  assets/California flag.gif
  assets/California intro.gif
  assets/Welcome to California.gif
  assets/california-beach.gif
  assets/california-flag 2.gif
Labels: documentation

#94 Update solutions/readme.md
  solutions/README.md
Labels: documentation, Polish

#95 All team readme
  README.md
Labels: documentation, enhancement, communication, update

#98 updating and adding Readme files for test files
  solutions/tests/README.md
Labels: documentation, communication, challenge

#99 Adding and creating a README.MD FILE for Tests
  solutions/tests/README.md
Labels: documentation, communication, challenge

#102 Add README for Notes Folder
  notes/README.md
Labels: documentation, communication, meeting, Polish

#104 update style of our group across all MD
  collaboration/README.md
  collaboration/communication.md
  collaboration/constraints.md
  collaboration/retrospective.md
  solutions/tests/README.md
Labels: documentation, Polish

#100 [docs] Add sections for Stop Doing, Continue Doing, and Start Doing.
  collaboration/retrospective.md
Labels: communication, Polish

#105 Update constraints.md
  collaboration/constraints.md
Labels: documentation, Polish

#106 Sum proper divisors
  solutions/tests/test_sum_proper_divisors.py
Labels: enhancement, update

#108 module headers, input statments, removed extra words
  .github/PULL_REQUEST_TEMPLATE.md
Labels: update
